# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "GitHub Pages Deploy"
on:
  push:
    branches:
      - "main"
    paths:
      - "schema/**"
  workflow_dispatch:
concurrency:
  group: "github-pages-deploy"
  cancel-in-progress: false
jobs:
  main:
    name: "Main"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: "${{steps.deployment.outputs.page_url}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v6"
      - name: "Configure GitHub Pages"
        uses: "actions/configure-pages@v5"
      - name: "Upload GitHub Pages Artifact"
        uses: "actions/upload-pages-artifact@v4"
        with:
          path: "schema/"
      - name: "Deploy GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
